export const NOTIFICATION_TYPES = {
  SYSTEM: "SYSTEM",

  RETURN_REQUEST: "RETURN_REQUEST",
  RETURN_APPROVED: "RETURN_APPROVED",
  RETURN_REJECTED: "RETURN_REJECTED",
  RETURN_COMPLETED: "RETURN_COMPLETED",

  VOID_REQUEST: "VOID_REQUEST",
  VOID_APPROVED: "VOID_APPROVED",
  VOID_REJECTED: "VOID_REJECTED",
  VOID_COMPLETED: "VOID_COMPLETED",

  DISCOUNT_REQUEST: "DISCOUNT_REQUEST",
  DISCOUNT_APPROVED: "DISCOUNT_APPROVED",
  DISCOUNT_REJECTED: "DISCOUNT_REJECTED",

  LOW_STOCK: "LOW_STOCK",

  SHIFT: "SHIFT",

  SECURITY: "SECURITY",
};


export const NOTIFICATION_PRIORITIES = {
  LOW: "LOW",
  NORMAL: "NORMAL",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
};